"""Emit docs/assets/data.js for the GitHub Pages build.

Unlike the artifact build there is no CSP to work around: logos come straight
from ESPN's CDN and live odds are fetched in the browser, so the only thing
baked in is the schedule, the byes, the club accents, and a seed snapshot that
gives the page something to draw before the first fetch lands.
"""
import json, io, os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "docs", "assets", "data.js")

data = json.load(open(os.path.join(HERE, "data2026.json")))
art = json.load(open(os.path.join(HERE, "logos.json")))
meta = json.load(open(os.path.join(HERE, "live", "meta.json")))
seed = {str(w): json.load(open(os.path.join(HERE, "live", "w%d.json" % w))) for w in range(1, 19)}

# ESPN logo slugs: lowercase abbreviation, except Washington
SLUG = {t: ("wsh" if t == "WAS" else t.lower()) for t in art["light"]}

j = lambda o: json.dumps(o, separators=(",", ":"), sort_keys=True)
body = "\n".join([
    "/* Generated by tools/build_site.py - do not edit by hand. */",
    "export const SCHED = %s;" % j(data["games"]),
    "export const BYES = %s;" % j(data["byes"]),
    "export const ACCENTS = %s;" % j(art["accents"]),
    "export const SLUG = %s;" % j(SLUG),
    "export const SEED = %s;" % j(seed),
    "export const SEED_AT = %s;" % j(meta["fetched"]),
    "",
])
io.open(OUT, "w", encoding="utf-8").write(body)
print("data.js %.0f KB | %d games, 32 clubs, seed %s"
      % (os.path.getsize(OUT) / 1024, len(data["games"]), meta["fetched"]))
